// Objet pour stocker les valeurs d'attributes de base et de max en fonction du métatype
const characterData = {
  SIN: {},
  attributes: {
    body: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    agility: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    reaction: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    strength: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    willpower: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    logic: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    intuition: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    charisma: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    edge: {
      base: 1,
      added: 0,
      value: 1,
      max: 6,
    },
    magic: {
      base: 0,
      added: 0,
      value: 1,
      max: 6,
    },
    resonance: {
      base: 0,
      added: 0,
      value: 1,
      max: 6,
    },
  },
  skills: {
    firearms: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "agility",
      specializations: ["joie"],
      proposedSpecializations: ["teuf", "joie", "bigGuns"],
    },
    exoticWeapons: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "agility",
      specializations: [],
      proposedSpecializations: [],
    },
    astral: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "intuition",
      specializations: [],
      proposedSpecializations: [],
    },
    athletics: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "agility",
      specializations: [],
      proposedSpecializations: [],
    },
    biotech: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "logic",
      specializations: [],
      proposedSpecializations: [],
    },
    closeCombat: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "agility",
      specializations: [],
      proposedSpecializations: [],
    },
    conjuring: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "magic",
      specializations: [],
      proposedSpecializations: [],
    },
    electronics: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "logic",
      specializations: [],
      proposedSpecializations: [],
    },
    stealth: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "agility",
      specializations: [],
      proposedSpecializations: [],
    },
    influence: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "charisma",
      specializations: [],
      proposedSpecializations: [],
    },
    enchanting: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "magic",
      specializations: [],
      proposedSpecializations: [],
    },
    con: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "charisma",
      specializations: [],
      proposedSpecializations: [],
    },
    engineering: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "logic",
      specializations: [],
      proposedSpecializations: [],
    },
    peception: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "intuition",
      specializations: [],
      proposedSpecializations: [],
    },
    piloting: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "reaction",
      specializations: [],
      proposedSpecializations: [],
    },
    cracking: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "logic",
      specializations: [],
      proposedSpecializations: [],
    },
    outdoors: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "intuition",
      specializations: [],
      proposedSpecializations: [],
    },
    sorcery: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "magic",
      specializations: [],
      proposedSpecializations: [],
    },
    tasking: {
      base: 0,
      added: 0,
      value: 0,
      linkedAttribute: "resonance",
      specializations: [],
      proposedSpecializations: [],
    },
  },
  points: {
    skills: {
      base: 0,
      spent: 0,
    },
    Prio: {
      base: 0,
      spent: 0,
    },
    Adjustement: {
      base: 0,
      spent: 0,
    },
  },
  selectAttributeType: "Prio",
  alreadyMaxAttribute: "",
  alreadyMaxSkill: "",
  magicChoice: "",
  isMagic: false,
  isTechno: false,
  metatype: "",
  special: "",
};